title: Great Title Text
author: GitHub Lab Exercise
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Awesome description goes here.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  robleach # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
